Homework 1
================
Chufeng Yang

This is my solution to HM1 and my first R code\!

``` r
library(tidyverse)
```

    ## ─ Attaching packages ─────────────────────────── tidyverse 1.3.0 ─

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ─ Conflicts ──────────────────────────── tidyverse_conflicts() ─
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

Create a data frame

``` r
prob1_df =
tibble(
  samp = rnorm(10),
  samp_gt_0 = samp > 0,
  char_vec = c("a","b","c","d","e","f","g","h","i","j"),
  factor_vec = factor(c("red","red","red","green","green","green","blue","blue","blue","blue"))
)
```

Take the mean of each variable in my data frame

``` r
mean(pull(prob1_df, samp))
```

    ## [1] -0.1336268

``` r
mean(pull(prob1_df, samp_gt_0))
```

    ## [1] 0.4

``` r
mean(pull(prob1_df, char_vec))
```

    ## Warning in mean.default(pull(prob1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob1_df, factor_vec))
```

    ## Warning in mean.default(pull(prob1_df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

I can get the mean of number and logical but not character or factor.

``` r
as.numeric(pull(prob1_df, samp))
```

    ##  [1] -0.45910539 -0.80386466  0.29320683  2.39281918 -1.27006368 -1.15081999
    ##  [7]  0.01822089  1.93633907 -1.27871363 -1.01428634

``` r
as.numeric(pull(prob1_df, samp_gt_0))
```

    ##  [1] 0 0 1 1 0 0 1 1 0 0

``` r
as.numeric(pull(prob1_df, char_vec))
```

    ## Warning: 强制改变过程中产生了NA

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(prob1_df, factor_vec))
```

    ##  [1] 3 3 3 2 2 2 1 1 1 1

I can convert numbers, logical values and factors to numeric but not
characters.Logical values can be converted to 1 and 0, and can take a
meaningful mean, but character and factor maybe cannot.

``` r
as.numeric(pull(prob1_df, samp_gt_0))*pull(prob1_df, samp)
```

    ##  [1] 0.00000000 0.00000000 0.29320683 2.39281918 0.00000000 0.00000000
    ##  [7] 0.01822089 1.93633907 0.00000000 0.00000000

``` r
as.factor(pull(prob1_df, samp_gt_0))*pull(prob1_df, samp)
```

    ## Warning in Ops.factor(as.factor(pull(prob1_df, samp_gt_0)), pull(prob1_df, : '*'
    ## not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(as.factor(pull(prob1_df, samp_gt_0)))*pull(prob1_df, samp)
```

    ##  [1] -0.45910539 -0.80386466  0.58641366  4.78563836 -1.27006368 -1.15081999
    ##  [7]  0.03644177  3.87267815 -1.27871363 -1.01428634

## Problem 2

This is problem2 about inline R code, plotting and the behavior of
ggplot.

``` r
data("penguins", package = "palmerpenguins")
ls.str(penguins)
```

    ## bill_depth_mm :  num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
    ## bill_length_mm :  num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
    ## body_mass_g :  int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
    ## flipper_length_mm :  int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...
    ## island :  Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
    ## sex :  Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
    ## species :  Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
    ## year :  int [1:344] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...

The dataset is about Adelie :152 , Chinstrap: 68 , Gentoo :124 , NA, NA,
NA, NA, Biscoe :168 , Dream :124 , Torgersen: 52 , NA, NA, NA, NA, Min.
:32.10 , 1st Qu.:39.23 , Median :44.45 , Mean :43.92 , 3rd Qu.:48.50 ,
Max. :59.60 , NA’s :2 , Min. :13.10 , 1st Qu.:15.60 , Median :17.30 ,
Mean :17.15 , 3rd Qu.:18.70 , Max. :21.50 , NA’s :2 , Min. :172.0 , 1st
Qu.:190.0 , Median :197.0 , Mean :200.9 , 3rd Qu.:213.0 , Max. :231.0 ,
NA’s :2 , Min. :2700 , 1st Qu.:3550 , Median :4050 , Mean :4202 , 3rd
Qu.:4750 , Max. :6300 , NA’s :2 , female:165 , male :168 , NA’s : 11 ,
NA, NA, NA, NA, Min. :2007 , 1st Qu.:2007 , Median :2008 , Mean :2008 ,
3rd Qu.:2009 , Max. :2009 , NA.  
The dataset has 344 rows and 8 columns.  
The mean flipper length is 200.9152047

Make a scatterplot of flipper\_length\_mm (y) vs bill\_length\_mm (x),
color points using species as variable.

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_cy2588_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

``` r
ggsave("scatterplot_penguins.pdf")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

## HW1 done
